{
 "title": "Kafka Client Fetch Analysis",
 "time": { "from": "2019-06-19T19:14:00.000Z", "to": "2019-06-19T19:40:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "topic",
    "query": "query_result(kafka_cluster_partition_replicascount{kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"})"
   },
   {
    "name": "app",
    "label": "app",
    "query": "query_result(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic=~\"$topic\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Bytes Consumed Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{app=\"$app\",topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_total{app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Consumer Records Consumed Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{app=\"$app\",topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{app=\"$app\"}"
    }
   ]
  },
  {
   "title": "Broker Fetch Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=~\"$topic\", kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"}[1m])"
    }
   ]
  },
  {
   "title": "Broker Bytes Out Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"$topic\",kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"}[1m])"
    }
   ]
  }
 ]
}