apiVersion: apps/v1
kind: Deployment
metadata:
  name: producers
spec:
  selector:
    matchLabels:
      app:  producers
  replicas: 3
  template:
    metadata:
      labels:
        app: producers
    spec:
      containers:
        - command:
            - /opt/kafka/bin/kafka-producer-perf-test.sh
            - --topic
            - simple-topic
            - --num-records
            - "10000000"
            - --record-size
            - "67"
            - --throughput
            - "50000"
            - --producer-props
            - bootstrap.servers=pipelines-strimzi-kafka-bootstrap.lightbend.svc.cluster.local:9092
          image: strimzi/kafka
          imagePullPolicy: Always
          name: producers
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"