apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-kafka-240-snapshot
spec:
  selector:
    matchLabels:
      app:  producer-kafka-240-snapshot
  replicas: 3
  template:
    metadata:
      labels:
        app: producer-kafka-240-snapshot
    spec:
      containers:
        - command:
            - /opt/kafka/bin/kafka-producer-perf-test.sh
            - --topic
            - simple-topic-kafka-240-snapshot
            - --num-records
            - "10000000"
            - --record-size
            - "100"
            - --throughput
            - "50000"
            - --producer-props
            - bootstrap.servers=pipelines-strimzi-kafka-bootstrap.lightbend.svc.cluster.local:9092
          image: strimzi/kafka
          imagePullPolicy: Always
          name: producer-kafka-240-snapshot
          resources: {}